name: Build and deploy

concurrency:
  group: build-deploy-${{ github.ref_name }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci-workflow.yml
    secrets: inherit
